### ISSUE TITLE
Not able to send code

### ISSUE THREAD

**Issue by ThinkerDesigns** [y21/discordcaptcha#114]
The bot will say it has [@user You've already requested a verification code!].
but when i look in the wsl it says  @this error,

(node:30657) UnhandledPromiseRejectionWarning: Error: HTTP Exception: 403 (Missing Permissions)
    at RestRequest.send (/home/dhruv/discord/discordcaptcha/node_modules/detritus-client-rest/lib/request.js:193:27)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:30657) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:30657) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

if the creator is seeing this please help

**Comment by y21** [comment]
When are you getting that error? Does it happen when running the !verify command to request a captcha or when running it with a captcha as argument? Does the bot have enough permission?
Sadly the provided stack trace doesn't really help, since it just points to the library used to send requests to the Discord API.

Make sure the bots highest role is higher than the "verified" role. If the "verified" role is higher than the bots highest role, Discord won't let you assign the role to anyone. The role hierachy is important here.

GOOD: 
![image](https://user-images.githubusercontent.com/30553356/99901462-3a14a180-2cb7-11eb-9b94-9d128328e4de.png)

BAD: 
![image](https://user-images.githubusercontent.com/30553356/99901473-426cdc80-2cb7-11eb-86ca-359d7778223f.png)

**Comment by DSBUSA** [comment]
this happens when doing !verify.
And i do already have the bot higher than verify
![Screenshot (4)](https://user-images.githubusercontent.com/62044304/99929994-4a06a280-2d04-11eb-8f02-8ea95cfe20f0.png)
