### ISSUE TITLE
Why jimp?

### ISSUE THREAD

**Issue by misa-coder** [y21/discordcaptcha#99]
Jimp is a bit slow and not good for production usage. Can you please shift to canvas to create captcha images. There is an awesome repository [captcha-canvas](https://github.com/Shashank3736/captcha-canvas) to create captcha images which is also impossible to read by any ocr.

You can install captcha-canvas from npm.

**Comment by y21** [comment]
Jimp is used because it doesn't have any native dependencies and is written in pure JavaScript, which makes it very easy to build this project. I haven't done or looked at benchmarks for Jimp, but I can imagine `canvas` is more performant simply because it's written in native C++. The last time I checked though it seemed painful to setup for people who have never written a line of code before.
I'll try and see if it's worth switching to canvas later today.

**Comment by y21** [comment]
I thought I'd compare both libraries and as expected, `canvas` is much faster than Jimp.
![image](https://user-images.githubusercontent.com/30553356/93601964-3cf6cb80-f9c2-11ea-914a-fde258ef35fb.png)


For that reason I've created a separate branch on this repo ([canvas](https://github.com/y21/discordcaptcha/tree/canvas)) that uses canvas instead of Jimp, so just clone this branch for now until it's merged into the master branch (`git clone https://github.com/y21/discordcaptcha -b canvas`). I will add a note to the README that mentions this.

**Comment by misa-coder** [comment]
Thanks
